openapi: 3.0.1
info:
  title: Rate Quote API
  version: "1.0.0-public-preview"
  description: This file contains the schema definitions for the Full Truckload (FTL) Rate Quote API

tags:
  - name: Carrier API Standards
    description: Standards for Carrier APIs
paths:    
  /v1/ratequote/app:
    post:
      summary: Create a rate quote
      tags: 
        - Carrier API Standards 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/schema.yaml#/components/schemas/RateQuoteRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './schemas/schema.yaml#/components/schemas/RateQuoteResponse'
        '400':
          description: Error response
          content:
            application/json:
              schema:
                $ref: './schemas/schema.yaml#/components/schemas/RateQuoteErrorResponse'

  /v1/ratequote/app/{quoteId}:
    get: 
      summary: Get a rate quote
      tags: 
        - Carrier API Standards 
      operationId: getRateQuoteById
      parameters:
        - name: quoteId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './schemas/schema.yaml#/components/schemas/RateQuoteResponse'
        '404':
          description: Rate Quote Id not found
  
